/**
 * The commentary lexicon — the vocabulary of cricket prose the Stage-1 parser
 * pattern-matches (CLAUDE.md §4). Phrases are matched as whole words against
 * normalized text (lowercase, punctuation → single spaces), longest first, so
 * "short of a length" wins over "short" and "top edge" over "edge".
 *
 * Keep phrases lowercase, hyphen-free (normalization turns "mid-wicket" into
 * "mid wicket") and honest: a word goes in a list only when it reliably means
 * that thing in real commentary. Ambiguous words stay out — the ambiguity
 * policy is "wrong-but-plausible beats flashy-but-absurd".
 */
import type { SynthesizedShot } from "@/lib/providers/types";

export type ShotType = SynthesizedShot["shotType"];
export type DeliveryLength = SynthesizedShot["length"];
export type DeliveryLine = SynthesizedShot["line"];
export type Trajectory = SynthesizedShot["trajectory"];

/**
 * Shot vocabulary in match-priority order: when a line contains several verbs
 * ("goes for the pull, top edges it"), the earlier group wins. Edges and
 * misses outrank attacking verbs because the *result* of the swing is what we
 * animate; specific strokes outrank the generic drive/defend catch-alls.
 */
export const SHOT_GROUPS: ReadonlyArray<{ shot: ShotType; phrases: readonly string[] }> = [
  {
    shot: "edge",
    phrases: [
      "top edge",
      "top edges",
      "top edged",
      "outside edge",
      "inside edge",
      "under edge",
      "bottom edge",
      "leading edge",
      "thick edge",
      "thin edge",
      "faint edge",
      "edge",
      "edges",
      "edged",
      "nick",
      "nicks",
      "nicked",
      "snick",
      "snicks",
      "snicked",
      "feather",
      "feathers",
      "feathered",
      "chops on",
      "chopped on",
      "drags on",
      "dragged on",
      "plays on",
      "played on",
      "gets a tickle",
    ],
  },
  {
    shot: "missed",
    phrases: [
      "beaten",
      "beats the bat",
      "beats the outside",
      "beaten past the outside",
      "past the outside edge",
      "past the inside edge",
      "past the edge",
      "play and a miss",
      "swing and a miss",
      "swings and misses",
      "misses",
      "missed",
      "swishes at fresh air",
      "through the gate",
      "big appeal",
      "struck on the pad",
      "struck on the pads",
      "hits the pad",
      "hit on the pad",
      "raps the pads",
      "rapped on the pads",
      "trapped in front",
      "pinned in front",
      "plumb",
      "yorks him",
      "yorks her",
      "castled",
      "cleans him up",
      "cleans her up",
      "knocks back the",
      "rattles the stumps",
      "crashes into the stumps",
      "hits the top of off",
      "loses his off stump",
      "loses her off stump",
      "whips off the bails",
      "done in the flight",
      "bamboozled",
    ],
  },
  {
    shot: "leave",
    phrases: [
      "leaves",
      "leaves it alone",
      "left alone",
      "shoulders arms",
      "offers no shot",
      "no shot offered",
      "lets it go",
      "lets it through",
      "watches it through to the keeper",
      "well left",
      "left well alone",
    ],
  },
  {
    shot: "sweep",
    phrases: [
      "reverse sweep",
      "reverse sweeps",
      "reverse swept",
      "reverse sweeping",
      "slog sweep",
      "slog sweeps",
      "slog swept",
      "paddle sweep",
      "sweeps",
      "sweeping",
      "swept",
      "sweep",
      "paddles",
      "paddled",
      "paddle",
      "laps it",
      "lapped",
      "lap shot",
      "scoops",
      "scooped",
      "scoop",
      "ramps",
      "ramped",
      "ramp shot",
      "reverse ramps",
      "switch hit",
      "switch hits",
    ],
  },
  {
    shot: "pull",
    phrases: ["pulls", "pulled", "pull shot", "pull", "hooks", "hooked", "hook shot", "hook", "swivel pulls", "short arm jab", "short arm pull"],
  },
  {
    shot: "cut",
    phrases: [
      "upper cut",
      "upper cuts",
      "uppercut",
      "late cut",
      "late cuts",
      "square cut",
      "square cuts",
      "cuts",
      "cut away",
      "cut hard",
      "slashes",
      "slashed",
      "slash",
      "steers",
      "steered",
      "steer",
      "dabs",
      "dabbed",
      "dab",
      "guides",
      "guided",
      "runs it down",
      "run down to third",
      "opens the face",
    ],
  },
  {
    shot: "flick",
    phrases: [
      "flicks",
      "flicked",
      "flick",
      "whips",
      "whipped",
      "whip",
      "clips",
      "clipped",
      "clip",
      "glances",
      "glanced",
      "glance",
      "tickles",
      "tickled",
      "tickle",
      "nudges",
      "nudged",
      "nudge",
      "works it",
      "worked away",
      "works away",
      "worked off the pads",
      "works off the pads",
      "turns it off",
      "tucks",
      "tucked",
      "off the pads",
      "off his pads",
      "off her pads",
      "wristy",
    ],
  },
  {
    shot: "slog",
    phrases: [
      "slogs",
      "slogged",
      "slog",
      "heaves",
      "heaved",
      "heave",
      "mows",
      "mowed",
      "mow",
      "hoicks",
      "hoicked",
      "hoick",
      "swipes",
      "swiped",
      "swipe",
      "carts",
      "carted",
      "tonks",
      "tonked",
      "clobbers",
      "clobbered",
      "bludgeons",
      "bludgeoned",
      "muscles it",
      "muscled",
      "wild swing",
      "haymaker",
      "agricultural",
    ],
  },
  {
    shot: "loft",
    phrases: [
      "lofts",
      "lofted drive",
      "lofted straight",
      "lofted over",
      "lofted down the ground",
      "chips",
      "chipped",
      "chip over",
      "launches",
      "launched",
      "deposits",
      "deposited",
      "goes downtown",
      "goes big",
      "goes aerial",
      "takes on the",
      "inside out over",
      "lifts it over",
      "hits it over",
    ],
  },
  {
    shot: "drive",
    phrases: [
      "cover drive",
      "cover drives",
      "cover driven",
      "on drive",
      "on drives",
      "off drive",
      "off drives",
      "straight drive",
      "straight drives",
      "square drive",
      "square drives",
      "drives",
      "driven",
      "drive",
      "creams",
      "creamed",
      "caresses",
      "caressed",
      "strokes",
      "stroked",
      "punches",
      "punched",
      "punch",
      "smokes",
      "smoked",
      "thumps",
      "thumped",
      "hammers",
      "hammered",
      "spanks",
      "spanked",
      "crunches",
      "crunched",
      "blasts",
      "blasted",
      "smashes",
      "smashed",
      "strikes it",
      "threads",
      "threaded",
      "pierces",
      "pierced",
      "times it",
      "timed to perfection",
      "sweetly timed",
    ],
  },
  {
    shot: "defend",
    phrases: [
      "defends",
      "defended",
      "defensive",
      "defensively",
      "fends",
      "fended",
      "blocks",
      "blocked",
      "block",
      "dead bat",
      "dead bats",
      "solid defence",
      "solid defense",
      "forward defensive",
      "prods",
      "prodded",
      "taps it",
      "tapped",
      "pushes to",
      "pushed to",
      "pushes it",
      "pushed defensively",
      "drops it",
      "dropped it at",
      "keeps it out",
      "keeps out",
      "digs it out",
      "digs out",
      "dug out",
      "smothers",
      "smothered",
      "watchful",
    ],
  },
];

/** Spin-delivery vocabulary. "flatter"/"tossed up" etc. only ever describe spinners. */
export const SPIN_WORDS: readonly string[] = [
  "googly",
  "leg break",
  "legbreak",
  "leg spinner",
  "legspinner",
  "leg spin",
  "legspin",
  "off break",
  "offbreak",
  "off spinner",
  "offspinner",
  "off spin",
  "offspin",
  "doosra",
  "carrom ball",
  "carrom",
  "arm ball",
  "top spinner",
  "topspinner",
  "wrong un",
  "wrong'un",
  "wrongun",
  "slider",
  "flipper",
  "flighted",
  "flights it",
  "flights one",
  "gives it air",
  "gave it air",
  "tossed up",
  "tosses it up",
  "tosses this up",
  "loopy",
  "looped",
  "flatter",
  "darted in",
  "darts it in",
  "fired in",
  "fires it in",
  "turns away",
  "turns in",
  "turns past",
  "turns sharply",
  "turning ball",
  "turning",
  "big turn",
  "rips",
  "ripper",
  "ripped",
  "spins away",
  "spins in",
  "spins past",
  "spinner",
  "quicker one",
  "quicker ball",
  "undercutter",
  "out of the rough",
  "drifts in",
  "drifts away",
  "drift and dip",
  "dips on",
];

/** Pace-delivery vocabulary. */
export const PACE_WORDS: readonly string[] = [
  "outswinger",
  "inswinger",
  "outswing",
  "inswing",
  "away swing",
  "reverse swing",
  "swings away",
  "swings in",
  "swinging",
  "seams away",
  "seams in",
  "seam movement",
  "off the seam",
  "nips away",
  "nips in",
  "nips back",
  "jags back",
  "jags away",
  "shapes away",
  "shapes in",
  "angles in",
  "angles across",
  "angled in",
  "angled across",
  "bouncer",
  "bumper",
  "short pitched",
  "back of a length",
  "hard length",
  "heavy ball",
  "slower ball",
  "slower one",
  "off cutter",
  "leg cutter",
  "cutter",
  "cross seam",
  "express pace",
  "sheer pace",
  "raw pace",
  "searing pace",
  "sharp bouncer",
  "climbs on",
  "rising delivery",
  "steep bounce",
  "extra bounce",
  "skids on",
  "skiddy",
  "hurried the batter",
  "hurries him",
  "hurries her",
  "kph",
  "mph",
  "beats him for pace",
  "beats her for pace",
  "hits the deck",
  "bangs it in",
  "banged in short",
  "dug in short",
  "pace like fire",
];

export const LENGTH_GROUPS: ReadonlyArray<{ length: DeliveryLength; phrases: readonly string[] }> = [
  {
    length: "yorker",
    phrases: ["yorker", "yorkers", "yorked", "in the blockhole", "blockhole", "toe crusher", "at the base of", "right at the toes", "yorks"],
  },
  {
    length: "bouncer",
    phrases: ["bouncer", "bumper", "sharp bouncer", "climbs at the throat", "at the helmet", "throat ball", "chin music"],
  },
  {
    length: "short",
    phrases: [
      "short of a length",
      "short of length",
      "back of a length",
      "short ball",
      "short delivery",
      "drops short",
      "dropped short",
      "banged in",
      "banged in short",
      "dug in",
      "dug in short",
      "pulls back the length",
      "short and wide",
      "short and quick",
      "long hop",
      "hip high",
      "chest high",
      "rib cage",
      "at the ribs",
    ],
  },
  {
    length: "full",
    phrases: [
      "full toss",
      "full tosses",
      "low full toss",
      "beam",
      "half volley",
      "half volleys",
      "overpitched",
      "over pitched",
      "pitched up",
      "pitches it up",
      "very full",
      "full and straight",
      "full and wide",
      "full on",
      "full outside",
      "full length",
      "full delivery",
      "full ball",
      "fuller",
      "floated up",
      "floats it up",
      "drives on the up",
    ],
  },
  {
    length: "good",
    phrases: [
      "good length",
      "length ball",
      "length delivery",
      "on a length",
      "nagging length",
      "perfect length",
      "immaculate length",
      "hits the length",
      "top of off",
    ],
  },
];

export const LINE_GROUPS: ReadonlyArray<{ line: DeliveryLine; phrases: readonly string[] }> = [
  {
    line: "wide-off",
    phrases: [
      "wide outside off",
      "well outside off",
      "way outside off",
      "width outside off",
      "width on offer",
      "wide of off",
      "wide of the off stump",
      "short and wide",
      "full and wide",
      "wide yorker",
      "sprayed wide",
      "wide down the off side",
      "outside the tramline",
    ],
  },
  {
    line: "wide-leg",
    phrases: [
      "down the leg side",
      "down leg",
      "wide down leg",
      "sliding down leg",
      "slips down the leg",
      "strays down leg",
      "leg side wide",
      "wide on the pads",
    ],
  },
  {
    line: "off",
    phrases: [
      "outside off",
      "on off stump",
      "off stump line",
      "at off stump",
      "around off",
      "on off",
      "off pole",
      "fourth stump",
      "fifth stump",
      "in the channel",
      "in the corridor",
      "corridor of uncertainty",
      "top of off",
      "kissing off stump",
    ],
  },
  {
    line: "leg",
    phrases: [
      "on leg stump",
      "at leg stump",
      "leg stump line",
      "on the pads",
      "onto the pads",
      "on his pads",
      "on her pads",
      "at the pads",
      "on the hip",
      "into the hips",
      "at the body",
      "into the body",
      "leg side line",
      "straying onto the pads",
    ],
  },
  {
    line: "middle",
    phrases: [
      "on middle stump",
      "middle stump line",
      "on middle and leg",
      "middle and leg",
      "middle and off",
      "on the stumps",
      "at the stumps",
      "attacking the stumps",
      "stump to stump",
      "wicket to wicket",
      "dead straight",
      "on middle",
    ],
  },
];

/**
 * Trajectory resolves by GROUP priority (first group with any match), not by
 * phrase length: "steepling up over the keeper" is a skier even though "over
 * the keeper" is the longer lofted phrase. Order: skier → flat → lofted → ground.
 */
export const TRAJECTORY_GROUPS: ReadonlyArray<{ trajectory: Trajectory; phrases: readonly string[] }> = [
  {
    trajectory: "skier",
    phrases: [
      "skies it",
      "skied",
      "skies",
      "skyed",
      "up in the air",
      "straight up in the air",
      "steepling",
      "swirling",
      "swirls",
      "top edge high",
      "miles in the air",
      "ballooned",
      "balloons",
      "spirals up",
    ],
  },
  {
    trajectory: "flat",
    phrases: [
      "flat six",
      "flat hit",
      "flat and hard",
      "like a tracer bullet",
      "tracer bullet",
      "flat over",
      "bullet from the bat",
      "low and flat",
      "flat batted",
      "flat bat",
      "on a rope",
      "carries flat",
    ],
  },
  {
    trajectory: "lofted",
    phrases: [
      "lofted",
      "lofts",
      "in the air",
      "aerial",
      "over the top",
      "over the infield",
      "over the ring",
      "over the bowler",
      "over mid off",
      "over mid on",
      "over cover",
      "over extra cover",
      "over midwicket",
      "over mid wicket",
      "over square leg",
      "over long off",
      "over long on",
      "over fine leg",
      "over third man",
      "over the keeper",
      "over point",
      "over the rope",
      "over the ropes",
      "over the fence",
      "over the boundary",
      "into the stands",
      "into the crowd",
      "into the second tier",
      "onto the roof",
      "goes downtown",
      "deposits",
      "launches",
      "hangs in the air",
      "high and handsome",
      "clears",
      "chipped over",
      "chips over",
      "lifted over",
      "lifts it over",
    ],
  },
  {
    trajectory: "ground",
    phrases: [
      "along the ground",
      "along the carpet",
      "all along the ground",
      "keeps it down",
      "kept it down",
      "keeps it on the ground",
      "on the ground",
      "races away",
      "races to the",
      "raced away",
      "scorches",
      "scorched",
      "skims across",
      "skims along",
      "bisects the",
      "bobbles",
      "trickles",
      "rolls to",
      "dribbles",
      "scurries away",
      "runs away to the fence",
      "beats the dive",
      "past the diving",
      "one bounce into the",
      "bounces once and over",
    ],
  },
];

/**
 * Wicket-adjacent phrases that confirm the "batter advanced" stumping scene
 * (CLAUDE.md's reference: "Axar charges down the track ... Stumped!").
 */
export const ADVANCE_WORDS: readonly string[] = [
  "charges down",
  "dances down",
  "comes down the track",
  "down the track",
  "down the pitch",
  "down the wicket",
  "advances",
  "gives him the charge",
  "gives her the charge",
  "leaves his crease",
  "leaves her crease",
  "out of his crease",
  "out of her crease",
];
